### ISSUE TITLE
Creation d'un launcher d'application generic

### ISSUE THREAD

**Issue by miong** [miong/EpicProjects#2]
Le but de cette mission est simple.

Il faut s'inspirer du projet test qui est fonctionnel pour créer un lancer d'application libGDX générique.

Pour ce faire il faut créé deux projet : common.gdxLauncher.api et common.gdxLauncher.impl

 common.gdxLauncher.api contiendra l'ensemble des interface pour utiliser le lanceur et définir des application utilisant libGDX pour être lancer (méthode start, stop, pause, resume....)

common.gdxLauncher.impl contiendra l’implémentation du lanceur et l'ensemble des classes outils nécessaires.

Les projets devrons être des projets Maven et le code devra respecter l'ensemble des régles checkstyle  du projet.

Je pense que cela devrai te prendre environs 7 jours.

Courage et en cas de besoins ouvre une issues question.

**Comment by Fantur** [comment]
un, deux, trois..test

**Comment by miong** [comment]
Au fait du manque de réponse pour cet ticket, il est clôturé à l'état de non résolut et devant être réattribué.
